version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.7

    working_directory: ~/repo


    steps:
      - checkout
      - run:
          name: dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r test/requirements_test.txt
      - run:
          name: test
          command: |
            . venv/bin/activate
            python -m pytest test/